{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 06:48:46,583+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 06:49:10,947+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 06:49:40,183+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 06:50:14,169+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 06:50:37,921+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 06:52:31,200+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 06:56:45,788+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 07:21:38,246+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 07:21:44,665+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 07:21:47,460+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 07:23:52,241+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"subscribe() missing 1 required positional argument: 'symbols'","timestamp":"2024-04-30 07:52:35,343+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/code/fyersapi/consumers.py\", line 190, in on_open\n    self.fyers.subscribe(data_type=data_type)\nTypeError: subscribe() missing 1 required positional argument: 'symbols'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"subscribe() missing 1 required positional argument: 'symbols'","timestamp":"2024-04-30 07:52:52,678+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/code/fyersapi/consumers.py\", line 190, in on_open\n    self.fyers.subscribe(data_type=data_type)\nTypeError: subscribe() missing 1 required positional argument: 'symbols'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"subscribe() missing 1 required positional argument: 'symbols'","timestamp":"2024-04-30 07:54:11,266+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/code/fyersapi/consumers.py\", line 190, in on_open\n    Callback function to subscribe to data type and symbols upon WebSocket connection.\nTypeError: subscribe() missing 1 required positional argument: 'symbols'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"subscribe() missing 1 required positional argument: 'symbols'","timestamp":"2024-04-30 07:54:31,367+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/code/fyersapi/consumers.py\", line 190, in on_open\n    Callback function to subscribe to data type and symbols upon WebSocket connection.\nTypeError: subscribe() missing 1 required positional argument: 'symbols'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 08:43:21,409+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 08:43:45,103+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 08:43:51,995+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 08:44:03,486+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"onopen() missing 1 required positional argument: 'message'","timestamp":"2024-04-30 08:45:58,911+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: onopen() missing 1 required positional argument: 'message'","exception_name":"TypeError"}
{"level":"ERROR","location":"[__on_message:248] order_ws","message":"Expecting value: line 1 column 1 (char 0)","timestamp":"2024-05-01 06:35:43,118+0000","service":"FyersDataSocket"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"object of type 'NoneType' has no len()","timestamp":"2024-05-07 14:42:24,051+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 308, in __access_token_msg\n    buffer_size = 18 + len(self.__hsm_token) + len(self.source)\nTypeError: object of type 'NoneType' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"object of type 'NoneType' has no len()","timestamp":"2024-05-07 14:42:36,420+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 308, in __access_token_msg\n    buffer_size = 18 + len(self.__hsm_token) + len(self.source)\nTypeError: object of type 'NoneType' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'first_expiry_ts' referenced before assignment","timestamp":"2024-05-07 19:18:39,992+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/code/fyersapi/consumers.py\", line 152, in on_open\n    getdata = self.getOptionStrikes()\n  File \"/code/fyersapi/consumers.py\", line 199, in getOptionStrikes\n    \"timestamp\": first_expiry_ts\nUnboundLocalError: local variable 'first_expiry_ts' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'first_expiry_ts' referenced before assignment","timestamp":"2024-05-07 19:20:08,287+0000","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/code/fyersapi/consumers.py\", line 152, in on_open\n    getdata = self.getOptionStrikes()\n  File \"/code/fyersapi/consumers.py\", line 195, in getOptionStrikes\n    if first_expiry_ts:\nUnboundLocalError: local variable 'first_expiry_ts' referenced before assignment","exception_name":"UnboundLocalError"}
